all:
	g++  -std=c++17   ../Source/main.cpp    ../Source/Shader.cpp -o Output/binary/main  -lGL -lGLU -lglfw3 -lX11 -lXxf86vm -lXrandr -lpthread -lXi -ldl -lXinerama -lXcursor -lGLEW
clean:
	rm Output/binary/*