all:
	g++  -std=c++11   ../Source/*.cpp  ../System_Files/support_files/*.cpp  -O3 -o Output/binary/raytracer 
debug:
	g++  -std=c++11   ../Source/*.cpp  ../System_Files/support_files/*.cpp  -O3 -o Output/binary/raytracer_debug -g

clean:
	rm Output/binary/*